vpark/vpark/authenticate/urls.py
from django.urls import path
from . import views

app_name= "authenticate"
urlpatterns = [
    path('login/',views.Login,name="login"),
    path('signup/',views.Signup,name="signup"),
    path("logout/",views.Logout,name="logout"),
    # Profile
    path('profile/<int:pk>/',views.my_profile,name="profile"),
    path('profile/edit/<int:pk>/',views.update_profile,name="edit_profile"),
    path('profile/password/<int:pk>/',views.ChangePassword,name="change_password"),
    path('profile/photo/<int:pk>/',views.ChangeProfilePhoto,name="change_profile_photo")
]

vpark/vpark/booking/urls.py
from django.urls import path
from . import views

app_name = "booking"
urlpatterns = [
    path('register/location/',views.RegisterLocation,name="register_location"),
    path('location/',views.SelectLocation,name="select_location"),
    path('book/<int:pk>/',views.Booking,name="booking"),
]

vpark/vpark/gateway/urls.py
from django.urls import path
# Views import
from . import views

app_name = 'gateway'
urlpatterns = [
    path('entry/',views.EntryData,name="entry"),
    path('exit/',views.Exit,name="exit"),
    path('present/',views.Present_Vehicle,name="present"),
]

vpark/vpark/vpark/urls.py
from django.contrib import admin
from django.urls import path,include
# Static imports
from . import settings
from django.conf.urls.static import static
# Views Import
from .views import indexview
urlpatterns = [
    path('admin/', admin.site.urls),
    path('authenticate/',include('authenticate.urls')),
    path('gateway/',include('gateway.urls')),
    path('booking/',include('booking.urls')),
    path('',indexview,name='index'),

]

if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

vpark/vpark/authenticate/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.auth import get_user_model
# Create your models here.
class User_Signup(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE,related_name='user_content')
    name = get_user_model().first_name
    image = models.ImageField(upload_to='profile_photo/',null=True)
    phone = models.IntegerField(blank=True,null=True)
    mobile = models.IntegerField(blank=True,null=True)
    age = models.PositiveIntegerField(blank=True,null=True)
    address = models.TextField(blank=True,null=True)

class Contact(models.Model):
    name = models.CharField(max_length=256)
    email = models.EmailField(blank=True,null=True)
    subject = models.TextField(blank=True,null=True)
    message = models.TextField(blank=True,null=True)

vpark/vpark/authenticate/views.py
from django.shortcuts import render,reverse,redirect,get_object_or_404

# Model Imports
from django.contrib.auth.models import User
from .models import User_Signup
from booking.models import Book
# Login Imports
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.decorators import login_required

# Message Import
from django.contrib import messages

# Http Imports
from django.http import HttpResponse,HttpResponseRedirect
# Create your views here.

# Login
def Login(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username,password=password)
        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse("User is not active")
        else:
            messages.error(request,"Username Or Password is Invaild")
            return redirect('/authenticate/login/')

    return render(request,'authenticate/login.html')

# Signup
def Signup(request):
    if request.method == "POST":
        first_name = request.POST.get("first_name")
        last_name = request.POST.get("last_name")
        phone = request.POST.get("phone")
        address = request.POST.get("address")
        age = request.POST.get("age")
        mobile = request.POST.get("mobile")
        email = request.POST.get("email")
        username = request.POST.get("username")
        password = request.POST.get("password")
        try:
            image = request.FILES.get('myfiles')
            new = User(first_name=first_name,last_name=last_name,email=email,username=username)
            new.set_password(password)
            new.save()             # Optional Information
            extra = User_Signup(image=image,user=new,phone=phone,address=address,age=age,mobile=mobile)
            extra.save()
            return HttpResponseRedirect('/authenticate/login/')
        except:
            new = User(first_name=first_name, last_name=last_name, email=email, username=username)
            new.set_password(password)
            new.save()  # Optional Information
            extra = User_Signup(user=new, phone=phone, address=address, age=age, mobile=mobile)
            extra.save()
            return HttpResponseRedirect('/authenticate/login/')

    return render(request,'authenticate/signup.html')

@login_required(login_url='/authenticate/login/')
def Logout(request):
    logout(request)
    return HttpResponseRedirect('/authenticate/login/')

@login_required(login_url='/authenticate/login/')
def my_profile(request,pk):
    if request.user.is_superuser:
        user = get_object_or_404(User,pk=pk)
        other_info = get_object_or_404(User_Signup,pk=user.user_content.pk)
        book = Book.objects.filter(user=pk)
        return render(request,'authenticate/MyProfile.html',context={'book':book,'user_info':user,'other_info':other_info})
    else:
        user = get_object_or_404(User, pk=pk)
        other_info = get_object_or_404(User_Signup,pk=user.user_content.pk)
        return render(request, 'authenticate/MyProfile.html',
                      context={'user_info': user,'other_info':other_info})

@login_required(login_url='/authenticate/login/')
def update_profile(request,pk):
    user_info = get_object_or_404(User,pk=request.user.pk)
    other_info = get_object_or_404(User_Signup, pk=user_info.user_content.pk)
    if request.method == "POST":
        username = request.POST['username']
        phone = request.POST["phone"]
        address = request.POST['address']
        mobile = request.POST['mobile']
        email = request.POST['email']

        # User model
        user_info.username = username
        user_info.email = email
        # Custom Model
        other_info.phone = phone
        other_info.address = address
        other_info.mobile = mobile

        user_info.save()
        other_info.save()

        return HttpResponseRedirect('/authenticate/profile/'+str(pk))


    return render(request,'authenticate/edit_profile.html',context={'user_info':user_info,'other_info':other_info})

@login_required(login_url='/authenticate/login/')
def ChangePassword(request,pk):
    user = get_object_or_404(User,pk=request.user.pk)
    if request.method == "POST":
        password = request.POST['password']
        confirm_password = request.POST['confirm_password']
        if password != confirm_password:
            messages.error(request,'Password does not matched')
            return redirect('/authenticate/login/')
        else:
            user.set_password(password)
            user.save()
    return render(request,'authenticate/change_password.html')

@login_required(login_url='/authenticate/login/')
def ChangeProfilePhoto(request,pk):
    user0 = get_object_or_404(User,pk=request.user.pk)
    user = get_object_or_404(User_Signup,pk=user0.user_content.pk)
    if request.method == "POST" and request.FILES['profile_image']:
        image = request.FILES['profile_image']
        user.image = image
        user.save()
        return redirect('/authenticate/profile/'+str(pk))
    return render(request,'authenticate/change_profile_photo.html')

vpark/vpark/authenticate/templates/authenticate/MyProfile.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>My Profile</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href="{% static 'assets/img/favicon.pg' %}" rel="icon">
  <link href="{% static 'assets/img/apple-touch-icon.png' %}" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/icofont/icofont.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/animate.css/animate.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/remixicon/remixicon.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/line-awesome/css/line-awesome.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/venobox/venobox.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/owl.carousel/assets/owl.carousel.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/aos/aos.css' %}" rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href="{% static 'assets/css/style.css' %}" rel="stylesheet">


</head>

<body>

  <!-- ======= Header ======= -->
  <header id="header" class="fixed-top d-flex align-items-center">
    <div class="container d-flex align-items-center">

      <div class="logo mr-auto">
        <h1 class="text-light"><a href="index.html">VPARK</a></h1>
        <!-- Uncomment below if you prefer to use an image logo -->
        <!-- <a href="index.html"><img src="assets/img/logo.png" alt="" class="img-fluid"></a>-->
      </div>

      <nav class="nav-menu d-none d-lg-block">
        <ul class="">
          <li class=""><a href="{% url 'index' %}">Home</a></li>
          <li><a  href="{% url 'index' %}">About</a></li>
          <li><a  href="{% url 'index' %}">Services</a></li>
          <li><a  href="{% url 'index' %}">Pricing</a></li>

          <li><a  href="{% url 'index' %}">Contact</a></li>
          <li class=""><a href="{% url 'booking:select_location' %}">Book</a></li>
          <li class=""><a href="{% url 'booking:register_location' %}">Register Location</a></li>
          {% if user.is_superuser %}
          <li class=""><a href="{% url 'gateway:entry' %}">Entry</a></li>
          <li class=""><a href="{% url 'gateway:exit' %}">Exit</a></li>
          {% endif %}

		  {% if user.is_authenticated %}
          <li class="active"><a href="{% url 'authenticate:profile' pk=user.pk %}">Profile</a></li>
		  <li class=" btn-wrap active">
                <a href="{% url 'authenticate:logout' %}" class="btn-buy">Logout</a>
          </li>
          {% else %}
          <li class=" btn-wrap active">
                <a href="{% url 'authenticate:login' %}" class="btn-buy">LogIn</a>
          </li>
          {% endif %}
        </ul>
      </nav><!-- .nav-menu -->

    </div>
  </header><!-- End Header -->


<main id="main">

<!-- Profile Section -->
   <div class="container mt-5 pt-5">
    <div class="main-body mt-5">
    
          <div class="row gutters-sm">
            <div class="col-md-4 mb-3">
              <div class="card">
                <div class="card-body">
                  <div class="d-flex flex-column align-items-center text-center">
                    {% if other_info.image %}
                    <img src="{{ other_info.image.url }}" alt="Admin" class="mt-4 img-fluid rounded-circle">
                    {% else %}
                    <img src="https://bootdey.com/img/Content/avatar/avatar7.png" alt="Admin" class="mt-4 img-fluid rounded-circle">
                    {% endif %}
                    <div class="mt-3">
                      <h4>{{ first_name }} {{ last_name }}</h4>
                      
                    </div>
                  </div>
                </div>
              </div>
            </div>
			
            <div class="col-md-8">
              <div class="card mb-3">
                <div class="card-body">
                  <div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0">Full Name</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                      {{ user_info.first_name }} {{ user_info.last_name }}
                    </div>
                  </div>
                  <hr>
                  <div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0">Email</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                      {{ user_info.email }}
                    </div>
                  </div>
                  <hr>
                  <div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0">Phone</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                      {{ other_info.phone }}
                    </div>
                  </div>
                  <hr>
                  <div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0">Mobile</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                      {{ other_info.mobile }}
                    </div>
                  </div>
                  <hr>
                  <div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0">Address</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                      {{ other_info.address }}
                    </div>
                  </div>
                    <!-- Edit and Password -->
                    <hr>
                  <div class="row">
                    <div class="col-sm-4">
                        <a href="{% url 'authenticate:edit_profile' pk=user.pk %}" class="btn btn-primary">Edit</a>
                    </div>
                    <div class="col-sm-4">
                        <a href="{% url 'authenticate:change_profile_photo' pk=user.pk %}" class="btn btn-primary">Change Profile Photo</a>
                    </div>
                    <div class="col-sm-4 ">
                        <a href="{% url 'authenticate:change_password' pk=user.pk %}" class="btn btn-primary">Change Password</a>
                    </div>
                  </div>
                    <!-- End of edit and password -->
                </div>
              </div>
              
            </div>
          </div>
        </div>
    </div>
<!-- End of Profile Section -->

</main>
<!-- History -->
<section class="container">
  <table class="table ">
    <thead>
	 <tr>
	   <th scope="col">#</th>
	   <th scope="col">Place</th>
	   <th scope="col">Vechile</th>
	   <th scope="col">Vechile No.</th>
	   <th scope="col">Entry</th>
	   <th scope="col">Exit</th>
	   <th Scope="col">Total</th>
	 </tr>
	</thead>
	<tbody>
    <script>var i=1;</script>
    {% for book in book %}
	 <tr>
	  <th scope="row"><script>document.write(i);i++;</script></th>
	  <td> {{ book.location.location_name }}</td>
	  <td> {{ book.vehicle_type }}</td>
	  <td> {{ book.vehicle_no }}</td>
	  <td> {{ book.start_time }} </td>
	  <td> {{ book.end_time }} </td>
	  <td> {{ book.price }}rs </td>
	 </tr>
    {% endfor %}

	</tbody>
  </table>
</section>
<!-- End of History -->














  <!-- ======= Footer ======= -->
  <footer id="footer">
    <div class="container">
      <h3>VPARK</h3>
      <p>We are the official providers of parking. You can't park closer!</p>
      <div class="social-links">
        <a href="#" class="twitter"><i class="bx bxl-twitter"></i></a>
        <a href="#" class="facebook"><i class="bx bxl-facebook"></i></a>
        <a href="#" class="instagram"><i class="bx bxl-instagram"></i></a>
        <a href="#" class="google-plus"><i class="bx bxl-skype"></i></a>
        <a href="#" class="linkedin"><i class="bx bxl-linkedin"></i></a>
      </div>
      <div class="copyright">
        &copy; Copyright <strong><span>VPARK</span></strong>. All Rights Reserved
      </div>
      <div class="credits">
                Designed by <a href="https://bootstrapmade.com/">TeamMate</a>
      </div>
    </div>
  </footer><!-- End Footer -->

  <a href="#" class="back-to-top"><i class="ri-arrow-up-line"></i></a>

  <!-- Vendor JS Files -->
  <script src="{% static 'assets/vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'assets/vendor/jquery.easing/jquery.easing.min.js' %}"></script>
  <script src="{% static 'assets/vendor/php-email-form/validate.js' %}"></script>
  <script src="{% static 'assets/vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>
  <script src="{% static 'assets/vendor/venobox/venobox.min.js' %}"></script>
  <script src="{% static 'assets/vendor/owl.carousel/owl.carousel.min.js' %}"></script>
  <script src="{% static 'assets/vendor/aos/aos.js' %}"></script>

  <!-- Template Main JS File -->
  <script src="{% static 'assets/js/main.js' %}"></script>

</body>

</html>

vpark/vpark/authenticate/templates/authenticate/login.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>My Profile</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href="{% static 'assets/img/favicon.pg' %}" rel="icon">
  <link href="{% static 'assets/img/apple-touch-icon.png' %}" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/icofont/icofont.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/animate.css/animate.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/remixicon/remixicon.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/line-awesome/css/line-awesome.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/venobox/venobox.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/owl.carousel/assets/owl.carousel.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/aos/aos.css' %}" rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href="{% static 'assets/css/style.css' %}" rel="stylesheet">
  
  <!-- Template login css File -->
  <link href="{% static 'assets/css/login.css' %}" rel="stylesheet">


  
</head>

<body>

  <!-- ======= Header ======= -->
  <header id="header" class="fixed-top d-flex align-items-center">
    <div class="container d-flex align-items-center">

      <div class="logo mr-auto">
        <h1 class="text-light"><a href="{% url 'index' %}">VPARK</a></h1>
        <!-- Uncomment below if you prefer to use an image logo -->
        <!-- <a href="index.html"><img src="assets/img/logo.png" alt="" class="img-fluid"></a>-->
      </div>

      <nav class="nav-menu d-none d-lg-block">
        <ul class="">
          <li class=""><a href="{% url 'index' %}">Home</a></li>
          <li><a  href="{% url 'index' %}">About</a></li>
          <li><a  href="{% url 'index' %}">Services</a></li>
          <li><a  href="{% url 'index' %}">Pricing</a></li>

          <li><a  href="{% url 'index' %}">Contact</a></li>
          <li class=""><a href="{% url 'booking:select_location' %}">Book</a></li>
          <li class=""><a href="{% url 'booking:register_location' %}">Register Location</a></li>
          {% if user.is_superuser %}
          <li class=""><a href="{% url 'gateway:entry' %}">Entry</a></li>
          <li class=""><a href="{% url 'gateway:exit' %}">Exit</a></li>
          {% endif %}

		  {% if user.is_authenticated %}
            <li class=""><a href="{% url 'authenticate:profile' pk=user.pk %}">Profile</a></li>
		  <li class=" btn-wrap active">
                <a href="{% url 'authenticate:logout' %}" class="btn-buy">Logout</a>
          </li>
          {% else %}

          <li class=" btn-wrap active">
                <a href="{% url 'authenticate:login' %}" class="btn-buy">LogIn</a>
          </li>
          {% endif %}
        </ul>
      </nav><!-- .nav-menu -->

    </div>
  </header><!-- End Header -->


<main id="main">

<div class="limiter">
		<div class="d-flex justify-content-center">
			<div class="wrap-login100">
				<div class="login100-pic js-tilt" data-tilt>
					<img src="https://colorlib.com/etc/lf/Login_v1/images/img-01.png" alt="IMG">
				</div>

				<form method="POST" class=" validate-form">
                    {% csrf_token %}
					<span class="login100-form-title">
						Member Login
					</span>
                    <div class="">
                        {% for message in messages %}
                          <div class="alert alert-success">
                           <a class="close" href="#" data-dismiss="alert">×</a>

                           {{ message }}

                          </div>
                        {% endfor %}
                    </div>
					<div class="wrap-input100 validate-input">
						<input class="input100" type="text" name="username" placeholder="Username" required>
						<span class="focus-input100"></span>
						<span class="symbol-input100">
							<i class="fa fa-envelope" aria-hidden="true"></i>
						</span>
					</div>

					<div class="wrap-input100 validate-input" data-validate = "Password is required">
						<input class="input100" type="password" name="password" placeholder="Password" required>
						<span class="focus-input100"></span>
						<span class="symbol-input100">
							<i class="fa fa-lock" aria-hidden="true"></i>
						</span>
					</div>

					<div class="container-login100-form-btn">
						<button type="submit" class="login100-form-btn">
							Login
						</button>
					</div>

					<div class="text-center p-t-12">
						<span class="txt1">
							Forgot
						</span>
						<a class="txt2" href="#">
							Username / Password?
						</a>
					</div>

					<div class="text-center p-t-136">
						<a class="txt3" href="{% url 'authenticate:signup' %}">
							Create your Account
							<i class="fa fa-long-arrow-right m-l-5" aria-hidden="true"></i>
						</a>
					</div>
				</form>
			</div>
		</div>
	</div>

</main>














  <!-- ======= Footer ======= -->
  <footer id="footer">
    <div class="container">
      <h3>VPARK</h3>
      <p>We are the official providers of parking. You can't park closer!</p>
      <div class="social-links">
        <a href="#" class="twitter"><i class="bx bxl-twitter"></i></a>
        <a href="#" class="facebook"><i class="bx bxl-facebook"></i></a>
        <a href="#" class="instagram"><i class="bx bxl-instagram"></i></a>
        <a href="#" class="google-plus"><i class="bx bxl-skype"></i></a>
        <a href="#" class="linkedin"><i class="bx bxl-linkedin"></i></a>
      </div>
      <div class="copyright">
        &copy; Copyright <strong><span>VPARK</span></strong>. All Rights Reserved
      </div>
      <div class="credits">
                Designed by <a href="https://bootstrapmade.com/">TeamMate</a>
      </div>
    </div>
  </footer><!-- End Footer -->

  <a href="#" class="back-to-top"><i class="ri-arrow-up-line"></i></a>

  <!-- Vendor JS Files -->
  <script src="{% static 'assets/vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'assets/vendor/jquery.easing/jquery.easing.min.js' %}"></script>
  <script src="{% static 'assets/vendor/php-email-form/validate.js' %}"></script>
  <script src="{% static 'assets/vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>
  <script src="{% static 'assets/vendor/venobox/venobox.min.js' %}"></script>
  <script src="{% static 'assets/vendor/owl.carousel/owl.carousel.min.js' %}"></script>
  <script src="{% static 'assets/vendor/aos/aos.js' %}"></script>

  <!-- Template Main JS File -->
  <script src="{% static 'assets/js/main.js' %}"></script>

</body>

</html>