vpark/vpark/authenticate/urls.py
from django.urls import path
from . import views

app_name= "authenticate"
urlpatterns = [
    path('login/',views.Login,name="login"),
    path('signup/',views.Signup,name="signup"),
    path("logout/",views.Logout,name="logout"),
    # Profile
    path('profile/<int:pk>/',views.my_profile,name="profile"),
    path('profile/edit/<int:pk>/',views.update_profile,name="edit_profile"),
    path('profile/password/<int:pk>/',views.ChangePassword,name="change_password"),
    path('profile/photo/<int:pk>/',views.ChangeProfilePhoto,name="change_profile_photo")
]

vpark/vpark/booking/urls.py
from django.urls import path
from . import views

app_name = "booking"
urlpatterns = [
    path('register/location/',views.RegisterLocation,name="register_location"),
    path('location/',views.SelectLocation,name="select_location"),
    path('book/<int:pk>/',views.Booking,name="booking"),
]

vpark/vpark/gateway/urls.py
from django.urls import path
# Views import
from . import views

app_name = 'gateway'
urlpatterns = [
    path('entry/',views.EntryData,name="entry"),
    path('exit/',views.Exit,name="exit"),
    path('present/',views.Present_Vehicle,name="present"),
]

vpark/vpark/vpark/urls.py
from django.contrib import admin
from django.urls import path,include
# Static imports
from . import settings
from django.conf.urls.static import static
# Views Import
from .views import indexview
urlpatterns = [
    path('admin/', admin.site.urls),
    path('authenticate/',include('authenticate.urls')),
    path('gateway/',include('gateway.urls')),
    path('booking/',include('booking.urls')),
    path('',indexview,name='index'),

]

if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

vpark/vpark/gateway/models.py
from django.db import models
from django.contrib.auth.models import User
import datetime
from booking.models import Location
# Create your models here.


class Entry(models.Model):
    location = models.ForeignKey(Location,on_delete=models.CASCADE,null=True)
    vehicle_no = models.CharField(max_length=200)
    vehicle_type = models.CharField(max_length=300)
    mobile = models.IntegerField()
    tag_number = models.CharField(max_length=10,null=True)
    date = models.DateField(default=datetime.date.today)
    time = models.TimeField(default=datetime.datetime.now().strftime("%H:%M:%S"))

vpark/vpark/gateway/views.py
from django.shortcuts import render,get_object_or_404,redirect
# Http Imports
from django.http import HttpResponse
# Model Imports
from .models import Entry,Location
# Message Imports
from django.contrib import messages
# Date Imports
import datetime
# Login Imports
from django.contrib.auth.decorators import login_required
# Random imports
import string
import random
# Create your views here.
def random_char(y):
    return ''.join(random.choice(string.ascii_letters) for x in range(y))

def random_digits(n):
    range_start = 10**(n-1)
    range_end = (10**n)-1
    return random.randint(range_start, range_end)

@login_required(login_url='/authenticate/login/')
def EntryData(request):
    location_names = Location.objects.all()
    if request.method == "POST":
        vehicle_no = request.POST["vehicle_no"]
        vehicle_type = request.POST["vehicle_type"]
        select_location = request.POST["select_location"]
        mobile = request.POST["mobile"]
        date = datetime.date.today()
        time = datetime.datetime.now().time()


        tag_number = random_char(2) + str(random_digits(4))
        location = Location.objects.get(location_name=select_location)

        if vehicle_type == "Four Wheeler":
            location.four_space -= 1
        if vehicle_type == "Three Wheeler":
            location.three_space -= 1
        else:
            location.two_space -= 1

        enter = Entry(location=location,vehicle_no=vehicle_no,vehicle_type=vehicle_type,mobile=mobile,tag_number=tag_number)
        enter.save()
        return render(request,'gateway/entry_details.html',context={'time':time,'vehicle_no':vehicle_no,'vehicle_type':vehicle_type,'mobile':mobile,'tag_number':tag_number,'date':date})
    return render(request,'gateway/entry.html',context={'ln':location_names})



@login_required(login_url='/authenticate/login/')
def Exit(request):
    location_names = Location.objects.all()
    if request.method == "POST":
        vehicle_no = request.POST["vehicle_no"]
        vehicle_type = request.POST['vehicle_type']
        tag_number = request.POST['tag_number']
        mobile = request.POST['mobile']
        select_location = request.POST["select_location"]
        location = Location.objects.get(location_name=select_location)
        if len(Entry.objects.filter(location=location,vehicle_no=vehicle_no,vehicle_type=vehicle_type,tag_number=tag_number,mobile=mobile)) == 1:
            obj = Entry.objects.filter(vehicle_no=vehicle_no,vehicle_type=vehicle_type,tag_number=tag_number)
            model = get_object_or_404(obj,pk=obj[0].pk)
            model.delete()
            messages.success(request, "Vehicle Is Present")
            return redirect('/gateway/exit/')
        else:
            messages.success(request, "No Data Found")
            return redirect('/gateway/exit/')
    return render(request,'gateway/exit.html',context={'ln':location_names})

@login_required(login_url='/authenticate/login/')
def Present_Vehicle(request):
    vehicles = Entry.objects.all()
    return render(request,'gateway/present_vehicles.html',context={'vehicles':vehicles})

vpark/vpark/gateway/templates/gateway/entry.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>Gateway | Entry</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href="{% static 'assets/img/favicon.pg' %}" rel="icon">
  <link href="{% static 'assets/img/apple-touch-icon.png' %}" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/icofont/icofont.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/animate.css/animate.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/remixicon/remixicon.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/line-awesome/css/line-awesome.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/venobox/venobox.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/owl.carousel/assets/owl.carousel.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/aos/aos.css' %}" rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href="{% static 'assets/css/style.css' %}" rel="stylesheet">
  <link rel="stylesheet" href="{% static 'assets/css/signup.css' %}">
  
  <!-- Icons -->
  <link href="https://cdnjs.cloudflare.com/ajax/libs/simple-line-icons/2.4.1/css/simple-line-icons.min.css" rel="stylesheet">


</head>

<body>

  <!-- ======= Header ======= -->
  <header id="header" class="fixed-top d-flex align-items-center">
    <div class="container d-flex align-items-center">

      <div class="logo mr-auto">
        <h1 class="text-light"><a href="index.html">VPARK</a></h1>
        <!-- Uncomment below if you prefer to use an image logo -->
        <!-- <a href="index.html"><img src="assets/img/logo.png" alt="" class="img-fluid"></a>-->
      </div>

      <nav class="nav-menu d-none d-lg-block">
        <ul class="">
          <li class=""><a href="{% url 'index' %}">Home</a></li>
          <li><a  href="{% url 'index' %}">About</a></li>
          <li><a  href="{% url 'index' %}">Services</a></li>
          <li><a  href="{% url 'index' %}">Pricing</a></li>

          <li><a  href="{% url 'index' %}">Contact</a></li>
          <li class=""><a href="{% url 'booking:select_location' %}">Book</a></li>
          <li class=""><a href="{% url 'booking:register_location' %}">Register Location</a></li>
          {% if user.is_superuser %}
          <li class="active"><a href="{% url 'gateway:entry' %}">Entry</a></li>
          <li class=""><a href="{% url 'gateway:exit' %}">Exit</a></li>
          {% endif %}

		  {% if user.is_authenticated %}
          <li class=""><a href="{% url 'authenticate:profile' pk=user.pk %}">Profile</a></li>
		  <li class=" btn-wrap active">
                <a href="{% url 'authenticate:logout' %}" class="btn-buy">Logout</a>
          </li>
          {% else %}

          <li class=" btn-wrap active">
                <a href="{% url 'authenticate:login' %}" class="btn-buy">LogIn</a>
          </li>
          {% endif %}
        </ul>
      </nav><!-- .nav-menu -->

    </div>
  </header><!-- End Header -->
  
{% if user.is_superuser %}
  <!-- Sign UP -->
  <div class="registration-form social-media">
     <section>
        <form method="POST">
          {% csrf_token %}
            <div class="text-center pb-4">
                <span><h2>Vehicle Details</h2></span>
            </div>
			<hr class="hr-primary mb-3" />
            <div class="form-group pt-4">
                <input type="text" class="form-control item" id="username" placeholder="Vehicle Number" name="vehicle_no" required>
            </div>
            <!-- Vehicle Type -->
			<div class="form-group pt-4">
			 <select class="form-select form-control" aria-label="Vehicle Type" name="vehicle_type" style="border-radius:39px" required>
			  <option>Four Wheeler</option>
			  <option>Three Wheeler</option>
			  <option>Two Wheeler</option>
			 </select>
			</div>
			<!-- End of Vehicle Type -->

          <!-- Vehicle Type -->
			<div class="form-group pt-4">
			 <select class="form-select form-control" aria-label="Vehicle Type" name="select_location" style="border-radius:39px" required>
               {% for i in ln %}
			  <option>{{ i.location_name }}</option>
               {% endfor %}
			 </select>
			</div>
			<!-- End of Vehicle Type -->
            
			<div class="form-group pt-4">
                <input type="text" class="form-control item" id="mobile-number" placeholder="Mobile Number" name="mobile" required>
            </div>
			<div class="form-group pt-4">
                <button type="submit" class="btn btn-block create-account">Next</button>
            </div>


            <div class="form-group pt-4">
                <a href="{% url 'gateway:present' %}" class="btn btn-block create-account">Present Vehicles</a>
            </div>
        </form>

     </section>
    </div>
  <!-- End of Signup -->
  {% else %}
  <div class="registration-form social-media">
     <section>
       <div class="container">
         <div class="row">
           <div class="col text-center">
             <h3>You Are not and Admin!!</h3>
           </div>
         </div>
       </div>
     </section>
  </div>
  {% endif %}
  
  
  
  
  
  
  
   <!-- ======= Footer ======= -->
  <footer id="footer">
    <div class="container">
      <h3>VPARK</h3>
      <p>We are the official providers of parking. You can't park closer!</p>
      <div class="social-links">
        <a href="#" class="twitter"><i class="bx bxl-twitter"></i></a>
        <a href="#" class="facebook"><i class="bx bxl-facebook"></i></a>
        <a href="#" class="instagram"><i class="bx bxl-instagram"></i></a>
        <a href="#" class="google-plus"><i class="bx bxl-skype"></i></a>
        <a href="#" class="linkedin"><i class="bx bxl-linkedin"></i></a>
      </div>
      <div class="copyright">
        &copy; Copyright <strong><span>VPARK</span></strong>. All Rights Reserved
      </div>
      <div class="credits">
                Designed by <a href="https://bootstrapmade.com/">TeamMate</a>
      </div>
    </div>
  </footer><!-- End Footer -->

  <a href="#" class="back-to-top"><i class="ri-arrow-up-line"></i></a>

  <!-- Vendor JS Files -->
  <script src="{% static 'assets/vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'assets/vendor/jquery.easing/jquery.easing.min.js' %}"></script>
  <script src="{% static 'assets/vendor/php-email-form/validate.js' %}"></script>
  <script src="{% static 'assets/vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>
  <script src="{% static 'assets/vendor/venobox/venobox.min.js' %}"></script>
  <script src="{% static 'assets/vendor/owl.carousel/owl.carousel.min.js' %}"></script>
  <script src="{% static 'assets/vendor/aos/aos.js' %}"></script>

  <!-- Template Main JS File -->
  <script src="{% static 'assets/js/main.js' %}"></script>
  <script src="{% static 'assets/js/signup.js' %}"></script>
  
</body>

</html>

vpark/vpark/gateway/templates/gateway/exit.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>Gateway | Exit</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href="{% static 'assets/img/favicon.pg' %}" rel="icon">
  <link href="{% static 'assets/img/apple-touch-icon.png' %}" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/icofont/icofont.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/animate.css/animate.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/remixicon/remixicon.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/line-awesome/css/line-awesome.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/venobox/venobox.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/owl.carousel/assets/owl.carousel.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/aos/aos.css' %}" rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href="{% static 'assets/css/style.css' %}" rel="stylesheet">
  <link rel="stylesheet" href="{% static 'assets/css/signup.css' %}">
  
  <!-- Icons -->
  <link href="https://cdnjs.cloudflare.com/ajax/libs/simple-line-icons/2.4.1/css/simple-line-icons.min.css" rel="stylesheet">


</head>

<body>

  <!-- ======= Header ======= -->
  <header id="header" class="fixed-top d-flex align-items-center">
    <div class="container d-flex align-items-center">

      <div class="logo mr-auto">
        <h1 class="text-light"><a href="index.html">VPARK</a></h1>
        <!-- Uncomment below if you prefer to use an image logo -->
        <!-- <a href="index.html"><img src="assets/img/logo.png" alt="" class="img-fluid"></a>-->
      </div>

      <nav class="nav-menu d-none d-lg-block">
        <ul class="">
          <li class=""><a href="{% url 'index' %}">Home</a></li>
          <li><a  href="{% url 'index' %}">About</a></li>
          <li><a  href="{% url 'index' %}">Services</a></li>
          <li><a  href="{% url 'index' %}">Pricing</a></li>

          <li><a  href="{% url 'index' %}">Contact</a></li>
          <li class=""><a href="{% url 'booking:select_location' %}">Book</a></li>
          <li class=""><a href="{% url 'booking:register_location' %}">Register Location</a></li>
          {% if user.is_superuser %}
          <li class=""><a href="{% url 'gateway:entry' %}">Entry</a></li>
          <li class="active"><a href="{% url 'gateway:exit' %}">Exit</a></li>
          {% endif %}

		  {% if user.is_authenticated %}
          <li class=""><a href="{% url 'authenticate:profile' pk=user.pk %}">Profile</a></li>
		  <li class=" btn-wrap active">
                <a href="{% url 'authenticate:logout' %}" class="btn-buy">Logout</a>
          </li>
          {% else %}
          <li class=" btn-wrap active">
                <a href="{% url 'authenticate:login' %}" class="btn-buy">LogIn</a>
          </li>
          {% endif %}
        </ul>
      </nav><!-- .nav-menu -->

    </div>
  </header><!-- End Header -->
  
{% if user.is_superuser %}
  <!-- Sign UP -->
  <div class="registration-form social-media">
    <section>
        <form method="POST">
          {% csrf_token %}
            <div class="text-center pb-3">
                <span><h2>Vehicle Details</h2></span>
				<p class="mt-3"><strong>Please fill in the details below to get the details of vehicle</strong></p>
            </div>
			<hr class="hr-primary mb-3" />

          <!-- Success Message -->
                    <div class="">
                        {% for message in messages %}
                          <div class="alert alert-success">
                           <a class="close" href="#" data-dismiss="alert">×</a>

                           {{ message }}

                          </div>
                        {% endfor %}
                    </div>
          <!-- End of Success Message -->
            <div class="form-group pt-4">
                <input type="text" class="form-control item" id="vehicle_no" placeholder="Vehicle Number" name="vehicle_no" required>
            </div>
            <!-- Vehicle Type -->
			<div class="form-group pt-3">
			 <select class="form-select form-control" aria-label="Vehicle Type" name="vehicle_type" style="border-radius:39px" required>
			  <option>Four Wheeler</option>
			  <option>Three Wheeler</option>
			  <option>Two Wheeler</option>
			 </select>
			</div>
			<!-- End of Vehicle Type -->

          <!-- Vehicle Type -->
			<div class="form-group pt-4">
			 <select class="form-select form-control" aria-label="Vehicle Type" name="select_location" style="border-radius:39px" required>
               {% for i in ln %}
			  <option>{{ i.location_name }}</option>
               {% endfor %}
			 </select>
			</div>
			<!-- End of Vehicle Type -->

			<div class="form-group pt-3">
                <input type="text" class="form-control" id="mobile-number" placeholder="Mobile Number" name="mobile" required>
            </div>
			
			<div class="form-group pt-3">
                <input type="text" class="form-control item" id="tag-number" placeholder="Tag Number" name="tag_number" required>
            </div>
			<!-- Next and Print -->
            
			<div class="row">
			 <div class="col-6">
			  <div class="form-group pt-3">
                <button type="submit" class="btn btn-block create-account">Next</button>
              </div>
			 </div>
			 <div class="col-6">
			  <div class="form-group pt-3">
                <a href="{% url 'gateway:present' %}" class="btn btn-block create-account">Present Vehicles</a>
              </div>
			 </div>
			</div>
        </form>
    </section>
    </div>
  <!-- End of Signup -->
{% else %}
  <div class="registration-form social-media">
     <section>
       <div class="container">
         <div class="row">
           <div class="col text-center">
             <h3>You Are not and Admin!!</h3>
           </div>
         </div>
       </div>
     </section>
  </div>
  {% endif %}
  
  
  
  
  
  
  
   <!-- ======= Footer ======= -->
  <footer id="footer">
    <div class="container">
      <h3>VPARK</h3>
      <p>We are the official providers of parking. You can't park closer!</p>
      <div class="social-links">
        <a href="#" class="twitter"><i class="bx bxl-twitter"></i></a>
        <a href="#" class="facebook"><i class="bx bxl-facebook"></i></a>
        <a href="#" class="instagram"><i class="bx bxl-instagram"></i></a>
        <a href="#" class="google-plus"><i class="bx bxl-skype"></i></a>
        <a href="#" class="linkedin"><i class="bx bxl-linkedin"></i></a>
      </div>
      <div class="copyright">
        &copy; Copyright <strong><span>VPARK</span></strong>. All Rights Reserved
      </div>
      <div class="credits">
                Designed by <a href="https://bootstrapmade.com/">TeamMate</a>
      </div>
    </div>
  </footer><!-- End Footer -->

  <a href="#" class="back-to-top"><i class="ri-arrow-up-line"></i></a>

  <!-- Vendor JS Files -->
  <script src="{% static 'assets/vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'assets/vendor/jquery.easing/jquery.easing.min.js' %}"></script>
  <script src="{% static 'assets/vendor/php-email-form/validate.js' %}"></script>
  <script src="{% static 'assets/vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>
  <script src="{% static 'assets/vendor/venobox/venobox.min.js' %}"></script>
  <script src="{% static 'assets/vendor/owl.carousel/owl.carousel.min.js' %}"></script>
  <script src="{% static 'assets/vendor/aos/aos.js' %}"></script>

  <!-- Template Main JS File -->
  <script src="{% static 'assets/js/main.js' %}"></script>
  <script src="{% static 'assets/js/signup.js' %}"></script>
  
</body>

</html>