vpark/vpark/authenticate/urls.py
from django.urls import path
from . import views

app_name= "authenticate"
urlpatterns = [
    path('login/',views.Login,name="login"),
    path('signup/',views.Signup,name="signup"),
    path("logout/",views.Logout,name="logout"),
    # Profile
    path('profile/<int:pk>/',views.my_profile,name="profile"),
    path('profile/edit/<int:pk>/',views.update_profile,name="edit_profile"),
    path('profile/password/<int:pk>/',views.ChangePassword,name="change_password"),
    path('profile/photo/<int:pk>/',views.ChangeProfilePhoto,name="change_profile_photo")
]

vpark/vpark/booking/urls.py
from django.urls import path
from . import views

app_name = "booking"
urlpatterns = [
    path('register/location/',views.RegisterLocation,name="register_location"),
    path('location/',views.SelectLocation,name="select_location"),
    path('book/<int:pk>/',views.Booking,name="booking"),
]

vpark/vpark/gateway/urls.py
from django.urls import path
# Views import
from . import views

app_name = 'gateway'
urlpatterns = [
    path('entry/',views.EntryData,name="entry"),
    path('exit/',views.Exit,name="exit"),
    path('present/',views.Present_Vehicle,name="present"),
]

vpark/vpark/vpark/urls.py
from django.contrib import admin
from django.urls import path,include
# Static imports
from . import settings
from django.conf.urls.static import static
# Views Import
from .views import indexview
urlpatterns = [
    path('admin/', admin.site.urls),
    path('authenticate/',include('authenticate.urls')),
    path('gateway/',include('gateway.urls')),
    path('booking/',include('booking.urls')),
    path('',indexview,name='index'),

]

if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

vpark/vpark/booking/models.py
from django.db import models
from django.contrib.auth.models import User
import datetime
# Create your models here.
class Location(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE,null=True)
    location_name = models.CharField(max_length=500,unique=True)
    image = models.ImageField(upload_to='location_image/',null=True)
    location_address = models.TextField()
    location_link = models.CharField(max_length=800,null=True)
    four_space = models.IntegerField()
    two_space = models.IntegerField()
    three_space = models.IntegerField()
    mobile = models.IntegerField(null=True)
    phone = models.IntegerField(null=True)

    def __str__(self):
        return self.location_name


class Book(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE,null=True)
    location = models.ForeignKey(Location,on_delete=models.CASCADE)
    vehicle_type = models.CharField(max_length=200)
    vehicle_no = models.CharField(max_length=200,blank=True,null=True)
    date = models.DateField(default=datetime.date.today,blank=True,null=True)
    start_time = models.TimeField(default=datetime.datetime.now().strftime("%H:%M:%S"))
    end_time = models.TimeField(default=datetime.datetime.now().strftime("%H:%M:%S"))
    price = models.IntegerField(null=True)
    slots = models.IntegerField()

    def __str__(self):
        return self.user

vpark/vpark/booking/views.py
from django.shortcuts import render,get_object_or_404,reverse,redirect
# Http Imports
from django.http import HttpResponse,HttpResponseRedirect
# Razorpay
import razorpay
from django.views.decorators.csrf import csrf_exempt

# Login Imports
from django.contrib.auth.decorators import login_required
# Models Import
from .models import Location,Book
from authenticate.models import User_Signup
# Date Time Imports
import datetime


# Messages Import
from django.contrib import messages
# Create your views here.
@login_required(login_url='/authenticate/login/')
def RegisterLocation(request):
    if request.method == "POST" and request.FILES['myfiles']:
        location_name = request.POST["location_name"]
        location_address = request.POST["location_address"]
        four_space = request.POST["four_space"]
        two_space = request.POST["two_space"]
        three_space = request.POST["three_space"]
        phone = request.POST['phone']
        mobile = request.POST['mobile']
        image = request.FILES['myfiles']

        location = Location(image=image,user=request.user,phone=phone,mobile=mobile,location_name=location_name,location_address=location_address,four_space=four_space,two_space=two_space,three_space=three_space)
        location.save()
        messages.success(request, "Location Stored Successfully")
        return redirect('/booking/register/location/')
    return render(request,'booking/register_location.html')

# This is just used as function

@login_required(login_url='/authenticate/login/')
def booking_info(request):
    return render(request,'booking/booking_info.html')


@login_required(login_url='/authenticate/login/')
def Booking(request,pk):
    location = get_object_or_404(Location, pk=pk)
    vehicle_type_four = Book.objects.filter(location=location, vehicle_type="four_wheeler", date=datetime.date.today())
    vehicle_type_two = Book.objects.filter(location=location, vehicle_type="two_wheeler", date=datetime.date.today())
    vehicle_type_three = Book.objects.filter(location=location, vehicle_type="three_wheeler", date=datetime.date.today())
    four_space = location.four_space
    two_space = location.two_space
    three_space = location.three_space
    user = get_object_or_404(User_Signup,pk=request.user.pk)
    # Cost var
    less_6 = 0
    more_6 = 0
    more_12 = 0
    amount = 0
    if request.method == "POST":
        vehicle_type = request.POST["vehicle_type"]
        vehicle_no = request.POST["vehicle_no"]
        date = request.POST["date"]
        start_time = request.POST["start_time"]
        end_time = request.POST["end_time"]
        slots = request.POST["slots"]

        # Cost
        start_time = datetime.time(int(start_time[0:2]), int(start_time[3:]), 0)
        stop_time = datetime.time(int(end_time[0:2]), int(end_time[3:]), 0)

        date = datetime.date(2021,5,4)
        datetime1 = datetime.datetime.combine(date, start_time)
        datetime2 = datetime.datetime.combine(date, stop_time)
        time = datetime1 - datetime2
        time = str(time)
        hour = int(time[8:10])
        minute = int(time[11:13])

        print(vehicle_type)
        cost = 0
        if (vehicle_type == "Four Wheeler"):
            if (datetime.time(hour,minute,00) <= datetime.time(hour=6, minute=0, second=0)):
                cost = 30
            if (datetime.time(hour,minute,00) >= datetime.time(hour=6, minute=0,
                                                       second=0) and datetime.time(hour,minute,00) <= datetime.time(hour=12,
                                                                                                            minute=0,
                                                                                                            second=0)):
                cost = 50
            if (datetime.time(hour,minute,00) >= datetime.time(hour=12, minute=0, second=0)):
                cost = 60
            else:
                cost = 10
        else:
            cost = 20


        if (vehicle_type == "Two Wheeler"):
            if (datetime.time(hour,minute,00) <= datetime.time(hour=6, minute=0, second=0)):
                cost = 15
            if (datetime.time(hour,minute,00) >= datetime.time(hour=6, minute=0,
                                                       second=0) and datetime.time(hour,minute,00) <= datetime.time(hour=12,
                                                                                                            minute=0,
                                                                                                            second=0)):
                cost = 25
            if (datetime.time(hour,minute,00) >= datetime.time(hour=12, minute=0, second=0)):
                cost = 30
            else:
                cost = 10
        else:
            cost = 20

        if (vehicle_type == "Three Wheeler"):
            if (datetime.time(hour,minute,00) <= datetime.time(hour=6, minute=0, second=0)):
                cost = 20
            if (datetime.time(hour,minute,00) >= datetime.time(hour=6, minute=0,
                                                       second=0) and datetime.time(hour,minute,00) <= datetime.time(hour=12,
                                                                                                            minute=0,
                                                                                                            second=0)):
                cost = 35
            if (datetime.time(hour,minute,00) >= datetime.time(hour=12, minute=0, second=0)):
                cost = 40
            else:
                cost = 10
        else:
            cost = 20

        # RazorPay
        amount = cost * 100
        client = razorpay.Client(
            auth=("rzp_test_C9CpGpkPwIljXs", "BbmSDpdc0g4Bz8eUQkVFd04a"))
        payment = client.order.create({'amount': amount, 'currency': 'INR',
                                       'payment_capture': '1'})

        # Four Space
        # if booktime ends slot is made free for four_space.
        for i in range(len(vehicle_type_four)):
            if (vehicle_type_four[i].end_time >= datetime.datetime.strptime(datetime.datetime.now().strftime("%H:%M:%S"), '%H:%M:%S').time()):
                vehicle_type_four[i].location.four_space += 1
        # if booktime ends slot is made free for four_space.
            if (vehicle_type_four[i].start_time >= datetime.datetime.strptime(datetime.datetime.now().strftime("%H:%M:%S"), '%H:%M:%S').time()):
                vehicle_type_four[i].location.four_space -= 1

        # Two Space
        # if booktime ends slot is made free for two_space.
        for i in range(len(vehicle_type_two)):
            if (vehicle_type_two[i].end_time >= datetime.datetime.strptime(datetime.datetime.now().strftime("%H:%M:%S"), '%H:%M:%S').time()):
                vehicle_type_two[i].location.two_space += 1
        # if booktime ends slot is made free for two_space.
            if (vehicle_type_two[i].start_time >= datetime.datetime.strptime(datetime.datetime.now().strftime("%H:%M:%S"), '%H:%M:%S').time()):
                vehicle_type_two[i].location.two_space -= 1

        # Three Space
        # if booktime ends slot is made free for three_space.
        for i in range(len(vehicle_type_three)):
            if (vehicle_type_three[i].end_time >= datetime.datetime.strptime(datetime.datetime.now().strftime("%H:%M:%S"), '%H:%M:%S').time()):
                vehicle_type_three[i].location.three_space += 1
        # if booktime ends slot is made free for three_space.
            if (vehicle_type_three[i].start_time >= datetime.datetime.strptime(datetime.datetime.now().strftime("%H:%M:%S"), '%H:%M:%S').time()):
                vehicle_type_three[i].location.three_space -= 1

        # Booking
        if (vehicle_type == "Four Wheeler"):
            try:
                if (vehicle_type_four[0].location.four_space == 0):
                    messages.error(request,"No Space for Four Wheeler Left")
                    return redirect('/booking/book/'+str(pk))
                else:
                    book_space = Book(user=request.user,price=cost,location=location,vehicle_type=vehicle_type,vehicle_no=vehicle_no,date=date,start_time=start_time,end_time=end_time,slots=slots)
                    if location.four_space < int(slots):
                        messages.error(request, "No Space for Four Wheeler Left")
                        return redirect('/booking/book/' + str(pk))
                    else:
                        location.four_space = location.four_space - int(slots)
                        book_space.save()
                        return render(request,booking_info(request),
                                      context={"user":user,"vehicle_type_four": four_space - len(vehicle_type_four),
                                               "vehicle_type_two": two_space - len(vehicle_type_two),
                                               "vehicle_type_three": three_space - len(vehicle_type_three)
                                          , "cost": amount,"location":location,"vehicle_no":vehicle_no,"vehicle_type":vehicle_type
                                              ,'date':date,'in_time':start_time,'out_time':end_time})
            except:
                book_space = Book(user=request.user,price=cost, location=location, vehicle_type=vehicle_type,
                                  vehicle_no=vehicle_no, date=date, start_time=start_time, end_time=end_time,
                                  slots=slots)
                if location.four_space < int(slots):
                    messages.error(request, "No Space for Four Wheeler Left")
                    return redirect('/booking/book/' + str(pk))
                else:
                    location.four_space -= int(slots)
                    book_space.save()
                    return render(request, "booking/booking_info.html",

vpark/vpark/booking/templates/booking/booking_info.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>Booking | Details</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href="{% static 'assets/img/favicon.pg' %}" rel="icon">
  <link href="{% static 'assets/img/apple-touch-icon.png' %}" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/icofont/icofont.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/animate.css/animate.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/remixicon/remixicon.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/line-awesome/css/line-awesome.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/venobox/venobox.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/owl.carousel/assets/owl.carousel.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/aos/aos.css' %}" rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href="{% static 'assets/css/style.css' %}" rel="stylesheet">
  <link rel="stylesheet" href="{% static 'assets/css/signup.css' %}">

</head>

<body>

  <!-- ======= Header ======= -->
  <header id="header" class="fixed-top d-flex align-items-center">
    <div class="container d-flex align-items-center">

      <div class="logo mr-auto">
        <h1 class="text-light"><a href="index.html">VPARK</a></h1>
        <!-- Uncomment below if you prefer to use an image logo -->
        <!-- <a href="index.html"><img src="assets/img/logo.png" alt="" class="img-fluid"></a>-->
      </div>

      <nav class="nav-menu d-none d-lg-block">
        <ul class="">
          <li class=""><a href="{% url 'index' %}">Home</a></li>
          <li><a  href="{% url 'index' %}">About</a></li>
          <li><a  href="{% url 'index' %}">Services</a></li>
          <li><a  href="{% url 'index' %}">Pricing</a></li>

          <li><a  href="{% url 'index' %}">Contact</a></li>
          <li class="active"><a href="{% url 'booking:select_location' %}">Book</a></li>
          <li class=""><a href="{% url 'booking:register_location' %}">Register Location</a></li>
          {% if user.is_superuser %}
          <li class=""><a href="{% url 'gateway:entry' %}">Entry</a></li>
          <li class=""><a href="{% url 'gateway:exit' %}">Exit</a></li>
          {% endif %}

		  {% if user.is_authenticated %}
            <li class=""><a href="{% url 'authenticate:profile' pk=user.pk %}">Profile</a></li>
		  <li class=" btn-wrap active">
                <a href="{% url 'authenticate:logout' %}" class="btn-buy">Logout</a>
          </li>
          {% else %}

          <li class=" btn-wrap active">
                <a href="{% url 'authenticate:login' %}" class="btn-buy">LogIn</a>
          </li>
          {% endif %}
        </ul>
      </nav><!-- .nav-menu -->

    </div>
  </header><!-- End Header -->
  
  
  
  
  <!-- Sign UP -->
  <div class="registration-form social-media" style="padding-bottom:60px;margin-top-20px">
        <section>
            <form method="POST">
   <div class="row d-flex align-items-center justify-content-center">
    <div class="col">
	 <!-- Table -->
	 <table class="table table-hover table-bordered" style="border-radius:10px;font-size:1rem">
	    <!-- Table Title -->
	     <div class="text-center mb-4 pr-5 pb-3">
	      <h2>Vehicle Entry Details</h2>
	     </div>
	    <!-- End of Table Title -->
		<!-- Vehicle Number -->
         <tr>
          <th scope="row">Parking Loaction </th>
          <td>{{ location }}</td>
         </tr>
        <!-- Vehicle Number -->
         <tr>
          <th scope="row">Vehicle Number </th>
          <td>{{ vehicle_no }}</td>
         </tr>
         <!-- Vehicle Type -->
         <tr>
          <th scope="row">Vehicle Type</th>
          <td>{{ vehicle_type }}</td>
         </tr>
         <!-- Today's Date -->
         <tr>
          <th scope="row">In-Date</th>
          <td> {{ date }}</td>
         </tr>
         <!-- Time -->
         <tr>
          <th scope="row">In-Time</th>
          <td>{{ in_time }}</td>
         </tr>
         <!-- Mobile -->
         <tr>
          <th scope="row">Mobile Number</th>
          <td>{{ user.mobile }}</td>
         </tr>
  
  </table>
  <!-- End of Table -->
     <div class="row">

       <div class="col-12 form-group pt-3">
          <button id="rzp-button1" class="btn btn-block create-account">Book</button>
<script src="https://checkout.razorpay.com/v1/checkout.js"></script>
<script>
var options = {
    "key": "rzp_test_C9CpGpkPwIljXs",
    "amount": "{{ cost }}",
    "currency": "INR",
    "name": "VPARK",
    "description": "Test Transaction",
    "image": "https://example.com/your_logo",
    "order_id": "{{ payment.id }}",
    "handler": function (response){
        alert(response.razorpay_payment_id);
        alert(response.razorpay_order_id);
        alert(response.razorpay_signature)
    },
    "prefill": {
        "name": "Sachin Chougule",
        "email": "deepakchaudhari265@gmail.com",
        "contact": "1234567891"
    },
    "notes": {
        "address": "Razorpay Corporate Office"
    },
    "theme": {
        "color": "#3399cc"
    }
};
var rzp1 = new Razorpay(options);
rzp1.on('payment.failed', function (response){
        alert(response.error.code);
        alert(response.error.description);
        alert(response.error.source);
        alert(response.error.step);
        alert(response.error.reason);
        alert(response.error.metadata.order_id);
        alert(response.error.metadata.payment_id);
});
document.getElementById('rzp-button1').onclick = function(e){
    rzp1.open();
    e.preventDefault();
}
</script>
       </div>
     </div>
	</div>
   </div>
            </form>
        </section>
    </div>
  <!-- End of Signup -->

  
    <!-- ======= Footer ======= -->
  <footer id="footer">
    <div class="container">
      <h3>VPARK</h3>
      <p>We are the official providers of parking. You can't park closer!</p>
      <div class="social-links">
        <a href="#" class="twitter"><i class="bx bxl-twitter"></i></a>
        <a href="#" class="facebook"><i class="bx bxl-facebook"></i></a>
        <a href="#" class="instagram"><i class="bx bxl-instagram"></i></a>
        <a href="#" class="google-plus"><i class="bx bxl-skype"></i></a>
        <a href="#" class="linkedin"><i class="bx bxl-linkedin"></i></a>
      </div>
      <div class="copyright">
        &copy; Copyright <strong><span>VPARK</span></strong>. All Rights Reserved
      </div>
      <div class="credits">
                Designed by <a href="https://bootstrapmade.com/">TeamMate</a>
      </div>
    </div>
  </footer><!-- End Footer -->

  <a href="#" class="back-to-top"><i class="ri-arrow-up-line"></i></a>

  <!-- Vendor JS Files -->
  <script src="{% static 'assets/vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'assets/vendor/jquery.easing/jquery.easing.min.js' %}"></script>
  <script src="{% static 'assets/vendor/php-email-form/validate.js' %}"></script>
  <script src="{% static 'assets/vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>
  <script src="{% static 'assets/vendor/venobox/venobox.min.js' %}"></script>
  <script src="{% static 'assets/vendor/owl.carousel/owl.carousel.min.js' %}"></script>
  <script src="{% static 'assets/vendor/aos/aos.js' %}"></script>

  <!-- Template Main JS File -->
  <script src="{% static 'assets/js/main.js' %}"></script>
  <script src="{% static 'assets/js/signup.js' %}"></script>
</body>

</html>

vpark/vpark/booking/templates/booking/select_location.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>Select Location</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href="{% static 'assets/img/favicon.pg' %}" rel="icon">
  <link href="{% static 'assets/img/apple-touch-icon.png' %}" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/icofont/icofont.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/animate.css/animate.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/remixicon/remixicon.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/line-awesome/css/line-awesome.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/venobox/venobox.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/owl.carousel/assets/owl.carousel.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/aos/aos.css' %}" rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href="{% static 'assets/css/style.css' %}" rel="stylesheet">
  <link href="{% static 'assets/css/booking.css' %}" rel="stylesheet">
  <link href="{% static 'assets/css/select_location.css' %}" rel="stylesheet">
  
  
  <!-- Font awesome -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/all.min.css" rel="stylesheet">


</head>

<body>

  <!-- ======= Header ======= -->
  <header id="header" class="fixed-top d-flex align-items-center">
    <div class="container d-flex align-items-center">

      <div class="logo mr-auto">
        <h1 class="text-light"><a href="index.html">VPARK</a></h1>
        <!-- Uncomment below if you prefer to use an image logo -->
        <!-- <a href="index.html"><img src="assets/img/logo.png" alt="" class="img-fluid"></a>-->
      </div>

      <nav class="nav-menu d-none d-lg-block">
        <ul class="">
          <li class=""><a href="{% url 'index' %}">Home</a></li>
          <li><a  href="{% url 'index' %}">About</a></li>
          <li><a  href="{% url 'index' %}">Services</a></li>
          <li><a  href="{% url 'index' %}">Pricing</a></li>

          <li><a  href="{% url 'index' %}">Contact</a></li>
          <li class="active"><a href="{% url 'booking:select_location' %}">Book</a></li>
          <li class=""><a href="{% url 'booking:register_location' %}">Register Location</a></li>
          {% if user.is_superuser %}
          <li class=""><a href="{% url 'gateway:entry' %}">Entry</a></li>
          <li class=""><a href="{% url 'gateway:exit' %}">Exit</a></li>
          {% endif %}

		  {% if user.is_authenticated %}
          <li class=""><a href="{% url 'authenticate:profile' pk=user.pk %}">Profile</a></li>
		  <li class=" btn-wrap active">
                <a href="{% url 'authenticate:logout' %}" class="btn-buy">Logout</a>
          </li>
          {% else %}
          <li class=" btn-wrap active">
                <a href="{% url 'authenticate:login' %}" class="btn-buy">LogIn</a>
          </li>
          {% endif %}
        </ul>
      </nav><!-- .nav-menu -->

    </div>
  </header><!-- End Header -->
  
  <!-- Booking Details -->

<div class="container pb-5" style="padding-top:70px">
    <div class="contact__wrapper shadow-lg mt-n9">
        <div class="row no-gutters">
            
    
             <div class="col-lg-10 contact-form__wrapper p-5 order-lg-1">
                <form method="POST" class="contact-form form-validate" novalidate="novalidate">
                    {% csrf_token %}
				  <!-- Title -->
				  <div class="title text-center ml-5 pl-5 pb-5">
				    <h3 class="">Select Parking Location</h3>
					<p class="text-muted" style="font-size:0.8rem">You can't park closer instantly book your space today</p>
				  </div>
				  <!-- End of Title -->
				  <!-- Start of Cards -->

				   <!-- Card 1 -->
				<div class="row" style="margin-left:90px">
                    {% for i in location %}
	               <div class='col-sm-6 col-lg-4 mx-auto my-3'>
                    <div class='card card-shadow '>
	                 <div class='img-container'>
                       {% if i.image %}
	                  <img src="{{ i.image.url }}" alt="{% static 'assets/img/location.jpg' %}" class='card-img-top card-img'>
                       {% else %}
                      <img src="{% static 'assets/img/location.jpg' %}" class='card-img-top card-img'>
                       {% endif %}
	                 </div>
	                 <div class='card-body '>
	                   <div class='card-text text-center'>
                           <h5 class='diplay-4'><a href="{% url 'booking:booking' pk=i.pk %}">{{ i.location_name }}</a></h5>
                           <p>{{ i.location_address }}</p>
                           <a href="{{ i.location_link }}">Go To Maps</a>
	                 </div>
	                 </div>
	                </div>
                   </div>
                       {% endfor %}


				  <!-- End of Cards -->
                </div>
                </form>
			</div>
            </div>
			
            <!-- End Contact Form Wrapper -->
    
        </div>
    </div>

  <!-- End of Booking -->
  
  
  
    <!-- ======= Footer ======= -->
  <footer id="footer">
    <div class="container">
      <h3>VPARK</h3>
      <p>We are the official providers of parking. You can't park closer!</p>
      <div class="social-links">
        <a href="#" class="twitter"><i class="bx bxl-twitter"></i></a>
        <a href="#" class="facebook"><i class="bx bxl-facebook"></i></a>
        <a href="#" class="instagram"><i class="bx bxl-instagram"></i></a>
        <a href="#" class="google-plus"><i class="bx bxl-skype"></i></a>
        <a href="#" class="linkedin"><i class="bx bxl-linkedin"></i></a>
      </div>
      <div class="copyright">
        &copy; Copyright <strong><span>VPARK</span></strong>. All Rights Reserved
      </div>
      <div class="credits">
                Designed by <a href="https://bootstrapmade.com/">TeamMate</a>
      </div>
    </div>
  </footer><!-- End Footer -->

  <a href="#" class="back-to-top"><i class="ri-arrow-up-line"></i></a>

  <!-- Vendor JS Files -->
  <script src="{% static 'assets/vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'assets/vendor/jquery.easing/jquery.easing.min.js' %}"></script>
  <script src="{% static 'assets/vendor/php-email-form/validate.js' %}"></script>
  <script src="{% static 'assets/vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>
  <script src="{% static 'assets/vendor/venobox/venobox.min.js' %}"></script>
  <script src="{% static 'assets/vendor/owl.carousel/owl.carousel.min.js' %}"></script>
  <script src="{% static 'assets/vendor/aos/aos.js' %}"></script>

  <!-- Template Main JS File -->
  <script src="{% static 'assets/js/main.js' %}"></script>

</body>

</html>